spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "570346638219-0913qhfnv9amsc28lj6fk0b85rmjk3ab.apps.googleusercontent.com"
            client-secret: "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"

logging:
  level:
    org:
      springframework:
        web: TRACE
